branches:
  only:
    - master

services:
  - postgresql

addons:
  postgresql: "9.6"

language: java
jdk:
  - openjdk8

before_script:
  - psql -c 'create database user_db encoding=UTF8;' -U postgres
  - psql -c 'create database connector_hub_db encoding=UTF8;' -U postgres
  - psql -c 'create database webhook_db encoding=UTF8;' -U postgres

after_success:
  - ./gradlew jacocoTestReport coveralls

env:
  global:
    # COVERALLS_REPO_TOKEN
    - secure: "iOKVVO5aspSz2TjXMiUs3QFxSYt6imyeFz7h+kYJiqKS4byWELJJ90aWNtYR9kLy0WjR43ua8VVmn7KPJO5QA4d5UzEOse9P6jesebsljT4+25onD2La8JJO0m8XvZJb44wV/SgngEf/4t0jVfCIk8nt2IuqgmUNh5HAqYjoQUvnP738RvcaI+DW9pdyWFuytNKUeN3beE9kWXUQBeoat7npByh7eg5NmE8Ibn8RQFiqc5cHOlOMPWxY+XB5eXvuXskGt545nmKroL1We7VyF3VphPaZkXNRQvXmj8kJrc1UYX6okVUZi4PhfhdLciD4ZLZu9ohZN/H3Gi6tnnqp4UID3IccgPTkMV3MHrXHRYHIif5hwJN5pGtTpshAQRVDiR0yFgO/uloHOuLIUTLOB7FGvrHsLK7JhZQ9TxjbAX+Kwn75Gav05bcee6ogArGHyuo/72iXgw+Onzj3tQ5ytRZQ8pvGapKXSZlITJAbCLyvPM31AfRPgfRvvMMaKYAJ6KRCgjDaZz2g1FEAVdY7U0zhYCUsNOcMZ/PISaVw4Q9EB6Z2bsQUqGBPUVSQVIWeoPUhIzjI6PTzt7Gx9cQmTGsD0suBZZZG4LkM9KNzvKoEG8WEG6C+m+wddCROE2Mi3kK18CkDB/M57SyLcY36Gsh3knI8/Gpi0IRIVS/7hrc="
