server:
  port: 22027

spring:
  application:
    name: websocket-service

websocket:
  jetty:
    # 24 hours
    idle-timeout: 86400000
    # 8 Kb
    input-buffer-size: 8192
    # 1 min
    async-write-timeout: 60000
    # 64 Kb
    max-text-message-size: 65536
    # 32 Kb
    max-text-message-buffer-size: 32768
  amqp:
    # 30 min
    cleaner-frequency: 1800000
    webhook:
      # 1 min
      ack-timeout: 60000
      prefetch-count: 50
      consumerPoolSize: 3
