spring:
  rabbitmq:
    host: rabbitmq
  datasource:
    username: webhook_service
    password: 2tjIFJvsLpXTIf5B
    url: jdbc:postgresql://backend-stage.cp49urcbfang.us-east-2.rds.amazonaws.com:5432/webhook_db

security:
  oauth2:
    resource.jwt.key-value: "-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEApy3qbmDiHv1IwncR9Jy/mZ/8vMC+c6SN/Yl7Km4tAVEn5DzBQD7Zesa5mWfgpyREN1fyH05vrWwh6w1B5wNcM6Slz4kfvHgPfVyLBazAUMMBgYSoewZf5CCONi9AJeohEH6xsxlhR1RsBbsOpknDhOjF+qHh333Crq9G8DpTxmm+3a99m6a5u5JoYKY/uX6QJN9GnLoNKaMugclUcxGIBAwLXEncDBXOemfhf7SKYBsXBSLNRioQWKuzbIjNaqhCl3QKp8979PAOEfE4vH79ZTF8p5z/k+JmBFxMgulm4bDUDf8DaEg36SZjcmVIQBDQyzPyLdbJjvqzu0v+XdqilQIDAQAB\n-----END PUBLIC KEY-----"

webhook:
  base-url: https://stage.electrica.io/v1/webhooks

feign:
  userService.url: user-service:22022
  connectorHubService.url: connector-hub-service:22023
  invokerService.url: invoker-service:22024
  connectorService.url: connector-service:22025
  webhookService.url: webhook-service:22026
