version: 0.2

phases:
  pre_build:
    commands:
    - echo Logging in to Amazon ECR...
    - $(aws ecr get-login --no-include-email --region us-east-2)
  build:
    commands:
    - echo Build started on `date`
    - sh deploy/codebuild/define-profile.sh
    - chmod +x gradlew
    - sh deploy/docker/build.sh -p ${APP_PROFILE}
    - docker tag electrica/postgres:${APP_PROFILE} 251063236326.dkr.ecr.us-east-2.amazonaws.com/electrica/postgres:${APP_PROFILE}
    - docker tag electrica/common:${APP_PROFILE} 251063236326.dkr.ecr.us-east-2.amazonaws.com/electrica/common:${APP_PROFILE}
    - docker tag electrica/user-service:${APP_PROFILE} 251063236326.dkr.ecr.us-east-2.amazonaws.com/electrica/user-service:${APP_PROFILE}
    - docker tag electrica/connector-hub-service:${APP_PROFILE} 251063236326.dkr.ecr.us-east-2.amazonaws.com/electrica/connector-hub-service:${APP_PROFILE}
  post_build:
    commands:
    - echo Build completed on `date`
    - echo Pushing the Docker image...
    - docker push 251063236326.dkr.ecr.us-east-2.amazonaws.com/electrica/postgres:${APP_PROFILE}
    - docker push 251063236326.dkr.ecr.us-east-2.amazonaws.com/electrica/common:${APP_PROFILE}
    - docker push 251063236326.dkr.ecr.us-east-2.amazonaws.com/electrica/user-service:${APP_PROFILE}
    - docker push 251063236326.dkr.ecr.us-east-2.amazonaws.com/electrica/connector-hub-service:${APP_PROFILE}
