version: 0.2

phases:
  pre_build:
    commands:
    - echo Logging in to Amazon ECR...
    - $(aws ecr get-login --no-include-email --region us-east-2)
    - export APP_BRANCH=$(git rev-parse --abbrev-ref HEAD)
    - export APP_PROFILE=$APP_BRANCH
    - echo Execute build for profile $APP_PROFILE
  build:
    commands:
    - echo Build started on `date`
    - chmod +x gradlew
    - sh deploy/docker/build.sh -p dev
    - docker tag electrica/postgres:dev 251063236326.dkr.ecr.us-east-2.amazonaws.com/electrica/postgres:dev
    - docker tag electrica/common:dev 251063236326.dkr.ecr.us-east-2.amazonaws.com/electrica/common:dev
    - docker tag electrica/user-service:dev 251063236326.dkr.ecr.us-east-2.amazonaws.com/electrica/user-service:dev
    - docker tag electrica/connector-hub-service:dev 251063236326.dkr.ecr.us-east-2.amazonaws.com/electrica/connector-hub-service:dev
  post_build:
    commands:
    - echo Build completed on `date`
    - echo Pushing the Docker image...
    - docker push 251063236326.dkr.ecr.us-east-2.amazonaws.com/electrica/postgres:dev
    - docker push 251063236326.dkr.ecr.us-east-2.amazonaws.com/electrica/common:dev
    - docker push 251063236326.dkr.ecr.us-east-2.amazonaws.com/electrica/user-service:dev
    - docker push 251063236326.dkr.ecr.us-east-2.amazonaws.com/electrica/connector-hub-service:dev
