version: 0.2

phases:
  pre_build:
    commands:
    - echo Logging in to Amazon ECR...
    - $(aws ecr get-login --no-include-email --region us-east-2)
  build:
    commands:
    - echo Build started on `date`

    - echo AWS_DEFAULT_REGION = $AWS_DEFAULT_REGION
    - echo AWS_REGION = $AWS_REGION
    - echo CODEBUILD_BUILD_ARN = $CODEBUILD_BUILD_ARN
    - echo CODEBUILD_BUILD_ID = $CODEBUILD_BUILD_ID
    - echo CODEBUILD_BUILD_IMAGE = $CODEBUILD_BUILD_IMAGE
    - echo CODEBUILD_BUILD_SUCCEEDING = $CODEBUILD_BUILD_SUCCEEDING
    - echo CODEBUILD_INITIATOR = $CODEBUILD_INITIATOR
    - echo CODEBUILD_KMS_KEY_ID = $CODEBUILD_KMS_KEY_ID
    - echo CODEBUILD_LOG_PATH = $CODEBUILD_LOG_PATH
    - echo CODEBUILD_RESOLVED_SOURCE_VERSION = $CODEBUILD_RESOLVED_SOURCE_VERSION
    - echo CODEBUILD_SOURCE_REPO_URL = $CODEBUILD_SOURCE_REPO_URL
    - echo CODEBUILD_SOURCE_VERSION = $CODEBUILD_SOURCE_VERSION
    - echo CODEBUILD_SRC_DIR = $CODEBUILD_SRC_DIR
    - echo CODEBUILD_START_TIME = $CODEBUILD_START_TIME
    - echo HOME = $HOME

    - chmod +x gradlew
    - sh deploy/docker/build.sh -p dev
    - docker tag electrica/postgres:dev 251063236326.dkr.ecr.us-east-2.amazonaws.com/electrica/postgres:dev
    - docker tag electrica/common:dev 251063236326.dkr.ecr.us-east-2.amazonaws.com/electrica/common:dev
    - docker tag electrica/user-service:dev 251063236326.dkr.ecr.us-east-2.amazonaws.com/electrica/user-service:dev
    - docker tag electrica/connector-hub-service:dev 251063236326.dkr.ecr.us-east-2.amazonaws.com/electrica/connector-hub-service:dev
  post_build:
    commands:
    - echo Build completed on `date`
    - echo Pushing the Docker image...
    - docker push 251063236326.dkr.ecr.us-east-2.amazonaws.com/electrica/postgres:dev
    - docker push 251063236326.dkr.ecr.us-east-2.amazonaws.com/electrica/common:dev
    - docker push 251063236326.dkr.ecr.us-east-2.amazonaws.com/electrica/user-service:dev
    - docker push 251063236326.dkr.ecr.us-east-2.amazonaws.com/electrica/connector-hub-service:dev
