{{- define "common.configmap" -}}
{{- $common := dict "Values" .Values.common -}}
{{- $noCommon := omit .Values "common" -}}
{{- $overrides := dict "Values" $noCommon -}}
{{- $noValues := omit . "Values" -}}
{{- with merge $noValues $overrides $common -}}
kind: ConfigMap
apiVersion: v1
{{ template "common.metadata" . }}
data:
  spring.profiles.active: {{ .Values.global.profile }}
  feign.userService.url: user-service
  feign.connectorHubService.url: connector-hub-service
  feign.invokerService.url: invoker-service
  feign.connectorService.url: connector-service
  feign.webhookService.url: webhook-service
  feign.websocketService.url: webhook-service
  feign.metricService.url: metric-service
{{- range $key, $val := .Values.config.properties }}
  {{ $key }}: {{ $val }}
{{- end}}

{{- end -}}
{{- end -}}
