{{- define "common.secrets" -}}
{{- $common := dict "Values" .Values.common -}}
{{- $noCommon := omit .Values "common" -}}
{{- $overrides := dict "Values" $noCommon -}}
{{- $noValues := omit . "Values" -}}
{{- with merge $noValues $overrides $common -}}
apiVersion: v1
kind: Secret
type: Opaque
{{ template "common.metadata" . }}
data:
{{- range $key, $val := .Values.config.secrets }}
  {{ $key }}: {{ $val | b64enc }}
{{- end}}

{{- end -}}
{{- end -}}
