{{- define "common.secrets" -}}
apiVersion: v1
kind: Secret
type: Opaque
{{ template "common.metadata" . }}
data:
  {{- range $key, $val := .Values.global.secrets }}
    {{ $key }}: {{ $val | b64enc }}
  {{- end}}

{{- end -}}
