server:
  port: 22022

spring:
  application:
    name: user-service
  auth:
    keystore:
      path: classpath:keystore.jks
      secret: password
      key-alias: io.electrica
  datasource:
    name: pool-to-user-service
    username: postgres
    password: postgres
    url: jdbc:postgresql://127.0.0.1:5432/user_service
