server:
  port: 22022

spring:
  application:
    name: user-service
  auth:
    keystore:
      path: classpath:keystore.jks
      secret: change_me
      key-alias: coopel.com
  datasource:
    driver-class-name: org.h2.Driver
    password:
    url: "jdbc:h2:mem:localhost;DB_CLOSE_ON_EXIT=FALSE"
    username: admin
