spring:
  auth:
    keystore:
      path: file:./config/keystore.jks
      secret: 4EkY86Hx5yjmOPbV
      key-alias: io.electrica
  datasource:
    username: user_service
    password: U74bjT62SueESb62
    url: jdbc:postgresql://backend-stage.cp49urcbfang.us-east-2.rds.amazonaws.com:5432/user_db

feign:
  userService.url: user-service:22022
  connectorHubService.url: connector-hub-service:22023
  invokerService.url: invoker-service:22024
  connectorService.url: connector-service:22025
  webhookService.url: webhook-service:22026
