server:
  port: 22026

spring:
  application:
    name: webhook-service
  datasource:
    name: pool-to-webhook-db
    url: jdbc:postgresql://localhost:5432/webhook_db

webhook:
  base-url: http://localhost
  # 30 min
  message-ttl: 1800000
  # 24 hours
  queue-ttl: 86400000
