server:
  port: 22026

spring:
  application:
    name: webhook-service
  datasource:
    name: pool-to-webhook-db
    url: jdbc:postgresql://localhost:5432/webhook_db
webhook-service:
    webhookPrefixURL: https://webhooks.electrica.io/