server:
  port: 22026

spring:
  application:
    name: webhook-service
  datasource:
    name: pool-to-webhook-db
    url: jdbc:postgresql://localhost:5432/webhook_db

webhook:
  base-url: http://localhost
  message-result:
    # 1 hour
    max-timeout: 3600000
    amqp:
      prefetchCount: 250
