version: '3.1'

services:
  user-service:
    environment:
      - JAVA_OPTS=-Xmx128m
      - ARGS=--spring.datasource.url=jdbc:postgresql://postgres-db:5432/user_db
    ports:
      - 22022:22022
    links:
      - postgres-db

  connector-hub-service:
    environment:
      - JAVA_OPTS=-Xmx128m
      - ARGS=--spring.datasource.url=jdbc:postgresql://postgres-db:5432/connector_hub_db
    ports:
      - 22023:22023
    links:
      - postgres-db

  postgres-db:
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=
    ports:
      - 5432:5432
