version: '3.1'

services:
  user-service:
    image: ${ECR_HOST}electrica/user-service:dev
    environment:
      - JAVA_OPTS=-Xmx256m -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005
    ports:
      - 25022:5005

  connector-hub-service:
    image: ${ECR_HOST}electrica/connector-hub-service:dev
    environment:
      - JAVA_OPTS=-Xmx256m -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005
    ports:
      - 25023:5005

  invoker-service:
    image: ${ECR_HOST}electrica/invoker-service:dev
    environment:
      - JAVA_OPTS=-Xmx256m -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005
    ports:
      - 25024:5005

  connector-service:
    image: ${ECR_HOST}electrica/connector-service:dev
    environment:
      - JAVA_OPTS=-Xmx256m -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005
    ports:
      - 25025:5005

  postgres-db:
    image: ${ECR_HOST}electrica/postgres:dev

  gateway:
    image: ${ECR_HOST}electrica/gateway:dev