version: '3.1'

services:
  user-service:
    image: electrica/user-service:dev

  connector-hub-service:
    image: electrica/connector-hub-service:dev

  postgres-db:
    image: electrica/postgres:dev
