version: '3.1'

services:
  user-service:
    image: ${ECR_HOST}electrica/user-service:stage
    environment:
      - JAVA_OPTS=-Xmx512m -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005
      - ARGS=--common.swagger.host=${HOST_NAME:-localhost} --common.swagger.protocol=https
    ports:
      - 25022:5005

  connector-hub-service:
    image: ${ECR_HOST}electrica/connector-hub-service:stage
    environment:
      - JAVA_OPTS=-Xmx512m -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005
      - ARGS=--common.swagger.host=${HOST_NAME:-localhost} --common.swagger.protocol=https
    ports:
      - 25023:5005

  invoker-service:
    image: ${ECR_HOST}electrica/invoker-service:stage
    environment:
      - JAVA_OPTS=-Xmx512m -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005
      - ARGS=--common.swagger.host=${HOST_NAME:-localhost} --common.swagger.protocol=https
    ports:
      - 25024:5005

  connector-service:
    image: ${ECR_HOST}electrica/connector-service:stage
    environment:
      - JAVA_OPTS=-Xmx512m -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005
      - ARGS=--common.swagger.host=${HOST_NAME:-localhost} --common.swagger.protocol=https
    ports:
      - 25025:5005

  webhook-service:
    image: ${ECR_HOST}electrica/webhook-service:stage
    environment:
      - JAVA_OPTS=-Xmx512m -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005
      - ARGS=--common.swagger.host=${HOST_NAME:-localhost} --common.swagger.protocol=https
    ports:
      - 25026:5005

  websocket-service:
    image: ${ECR_HOST}electrica/websocket-service:stage
    environment:
      - JAVA_OPTS=-Xmx512m -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005
      - ARGS=--common.swagger.host=${HOST_NAME:-localhost} --common.swagger.protocol=https
    ports:
      - 25027:5005

  metric-service:
    image: ${ECR_HOST}electrica/metric-service:stage
    environment:
      - JAVA_OPTS=-Xmx512m -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005
      - ARGS=--common.swagger.host=${HOST_NAME:-localhost} --common.swagger.protocol=https
    ports:
      - 25028:5005

  rabbitmq:
    environment:
      - RABBITMQ_DEFAULT_USER=rabbitmq
      - RABBITMQ_DEFAULT_PASS=rabbitmq

  gateway:
    image: ${ECR_HOST}electrica/gateway:stage

  swagger-ui:
    environment:
      - "API_URLS=[ {url: \"https://${HOST_NAME:-localhost}/user-service/swagger/\", name: \"User\"}, {url: \"https://${HOST_NAME:-localhost}/connector-hub-service/swagger/\", name: \"Connector Hub\"}, {url: \"https://${HOST_NAME:-localhost}/invoker-service/swagger/\", name: \"Invoker\"}, {url: \"https://${HOST_NAME:-localhost}/webhook-service/swagger/\", name: \"Webhook\"}, {url: \"https://${HOST_NAME:-localhost}/metric-service/swagger/\", name: \"Metric\"} ]"
