version: '3.1'

services:
  user-service:
    ports:
      - 22022:22022

  connector-hub-service:
    ports:
      - 22023:22023

  invoker-service:
    depends_on:
      - rabbitmq
    ports:
      - 22024:22024

  connector-service:
    ports:
      - 22025:22025

  webhook-service:
    depends_on:
      - rabbitmq
    ports:
      - 22026:22026

  websocket-service:
    depends_on:
      - rabbitmq
    ports:
      - 22027:22027

  metric-service:
    depends_on:
      - rabbitmq
    ports:
      - 22028:22028

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - 15672:15672
      - 5672:5672

  gateway:
    environment:
      - "HOST_NAME=${HOST_NAME:-localhost}"
    depends_on:
      - swagger-ui
      - user-service
      - connector-hub-service
      - invoker-service
      - connector-service
      - webhook-service
      - websocket-service
    ports:
      - 80:80

  swagger-ui:
    image: swaggerapi/swagger-ui
    environment:
      - BASE_URL=/swagger
    ports:
      - 8080:8080
