version: '3.1'

services:
  user-service:
    image: electrica/user-service
    environment:
      - JAVA_OPTS=-Xmx256m -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005
    depends_on:
      - postgres-db
    ports:
      - 25022:5005

  connector-hub-service:
    image: electrica/connector-hub-service
    environment:
      - JAVA_OPTS=-Xmx256m -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005
    depends_on:
      - postgres-db
    ports:
      - 25023:5005

  invoker-service:
    image: electrica/invoker-service
    environment:
      - JAVA_OPTS=-Xmx256m -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005
    ports:
      - 25024:5005

  connector-service:
    image: electrica/connector-service
    environment:
      - JAVA_OPTS=-Xmx256m -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005
    ports:
      - 25025:5005

  webhook-service:
    image: electrica/webhook-service
    environment:
      - JAVA_OPTS=-Xmx256m -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005
    depends_on:
      - postgres-db
    ports:
      - 25026:5005

  websocket-service:
    image: electrica/websocket-service
    environment:
      - JAVA_OPTS=-Xmx256m -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005
    ports:
      - 25027:5005

  postgres-db:
    image: electrica/postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=
    ports:
      - 5432:5432

  rabbitmq:
    environment:
      - RABBITMQ_DEFAULT_USER=rabbitmq
      - RABBITMQ_DEFAULT_PASS=rabbitmq

  gateway:
    image: electrica/gateway

  swagger-ui:
    environment:
      - "API_URLS=[ {url: \"http://localhost/user-service/swagger/\", name: \"User\"}, {url: \"http://localhost/connector-hub-service/swagger/\", name: \"Connector Hub\"}, {url: \"http://localhost/invoker-service/swagger/\", name: \"Invoker\"}, {url: \"http://localhost/connector-service/swagger/\", name: \"Connector\"},{url: \"http://localhost/webhook-service/swagger/\", name: \"Webhook\"} ]"
