version: '3.1'

services:
  user-service:
    image: ${ECR_HOST}electrica/user-service:dev

  connector-hub-service:
    image: ${ECR_HOST}electrica/connector-hub-service:dev

  postgres-db:
    image: ${ECR_HOST}electrica/postgres:dev
